### ISSUE TITLE
mcunet-10fps inference failing shows nonperson always

### ISSUE THREAD

**Issue by brainchip-india** [mit-han-lab/tinyengine#18]
With the help of the [tinyengine/tutorial](https://github.com/mit-han-lab/tinyengine/tree/master/tutorial) I am able to run the mcunet_5ps(default) and able to see the inference is working fine, so tried changing model to mcunet_10fps in tinyengine/tutorial/examples/vww.py file able to run the code but the inference is failing (always showing no person though the person is present).

anything I need to take care to run mcunet_10fps? 
@meenchen @RaymondWang0 please help, thanks in advance.

![mcunet_10fps_failed](https://user-images.githubusercontent.com/109508165/202649855-f2efed9b-b529-4754-84f3-9d4879a2ccf6.png)

**Comment by brainchip-india** [comment]
@meenchen @RaymondWang0 not sure you both have seen the issue, kindly reminding the issue.

**Comment by meenchen** [comment]
Hi @brainchip-india,

In the tutorial, the application code assumes the resolution of the model is 80x80, but for mcunet_10fps, it is actually 64x64. You will need to change the data loading part in the main.cpp for different models.

**Comment by brainchip-india** [comment]
Thanks @meenchen it worked, it's better you log it somewhere in the Readme for newbies like me.
