### ISSUE TITLE
VWW demo and Arducam Shield Mini 2MP Plus

### ISSUE THREAD

**Issue by ahdxwg** [mit-han-lab/tinyengine#20]
I am very interested in your project and want to realize it.    I couldn't get the Arducam Shield Mini **2MP** Plus on Taobao.Can I use Arducam Shield Mini **5MP** Plus?

**Comment by ahdxwg** [comment]
![fe0c7c3d727acfbd30ebc8347439556](https://user-images.githubusercontent.com/115546189/204564620-7d5848e0-27bd-4193-a649-c036be5d87ab.jpg)
Could I use DEV-18440 ARDUCAM 5MP PLUS OV5642 MINI CAM ?Thanks

**Comment by meenchen** [comment]
Hi @ahdxwg,

Unfortunately, our demo only works with the 2MP camera, but recently we have released another [tutorial for OpenMV cam](https://github.com/mit-han-lab/tinyengine/tree/master/examples/openmv_vww). You should be able to get one OpenMV cam easily.

**Comment by meenchen** [comment]
Close due to inactivity. Feel free to reopen.
