### ISSUE TITLE
Profiling method?

### ISSUE THREAD

**Issue by rodonguyen** [mit-han-lab/tinyengine#24]
First of all, I love the project you are doing! 
So my question is: How do you profile the memory (and maybe storage) the model consumes?

I really appreciate any help you can provide.
Rodo

**Comment by rodonguyen** [comment]
Thanks a lot for the detailed answer! That's more than sufficient for my discovery.
Rodo

**Comment by meenchen** [comment]
Glad to hear it helps. I will close this issue since is solved.
