### ISSUE TITLE
some api used in "GeneralMemoryScheduler.py" 

### ISSUE THREAD

**Issue by waquey** [mit-han-lab/tinyengine#4]
Excuse me, I cannot trace the exact definition of the following api which are related to op 

layermem["MAC"] = op.get_macs()
layermem["activation"] = op.get_activation_size()
layermem["scale"] = op.get_scale_size()
layermem["runtime"] = op.get_sbuf_size()
layermem["kernel"] = op.get_kbuf_size()

Where can we find the definition of get_macs()/get_activation_size()/get_scale_size()/get_sbuf_size()/get_kbuf_size() ? 
Could you please help comment that? 
Thanks

**Comment by meenchen** [comment]
Hi @waquey, thanks for your interest in our work! Please refer to the implementation of operators in [code_generator/operators](https://github.com/mit-han-lab/tinyengine/tree/master/code_generator/operators). The abstraction of these APIs is in [code_generator/operators/basic_utils.py](https://github.com/mit-han-lab/tinyengine/blob/master/code_generator/operators/basic_utils.py).

**Comment by meenchen** [comment]
Close due to inactivity. Feel free to reopen.
