### ISSUE TITLE
How can I send "3" to the UART input for the stm32 MCU?

### ISSUE THREAD

**Issue by 729557989** [mit-han-lab/tinyengine#42]
Hi,

**Context:** I am new to this and going through the on-device training tutorial.

**Issue:** I am on this instruction: Send "3" to the UART input for the MCU: Training mode
Do I need to use another board to direct the UART communication? Or is there a PC app I can use to perform this UART communication?

Thanks!

**Comment by meenchen** [comment]
Hi @729557989,

If you are using macOS, please use `screen <COM port> 115200`. The port name should be something like `/dev/tty.usbmodemxxxx`. You can also use other tools like minicom to send the UART input.
