### ISSUE TITLE
Up-to-date ProxylessNAS models?

### ISSUE THREAD

**Issue by travisjayday** [mit-han-lab/tinyengine#5]
We're trying to run NAS ourselves using OFA, but you have not open-sourced up-to-date ProxylessNAS models used in the mcunet search. These would be helpful for us to re-create your results and use them in our projects. Are there plans to do this?

Thanks!

**Comment by tonylins** [comment]
Hi, thanks for reaching out. We are currently working on releasing the super network. However, it could take a while due to the API change in the codebase.

**Comment by meenchen** [comment]
Close due to inactivity. Feel free to reopen.
