### ISSUE TITLE
screen too dark

### ISSUE THREAD

**Issue by Super-Karl** [mit-han-lab/tinyengine#52]
Hi, thanks for your work.
I tried the tutorial without a camera and the MCU board is the same as yours. It can detect if there is a person in the picture. But the screen was too dark. Where can I adjust to make the screen brighter.

**Comment by meenchen** [comment]
Hi @Super-Karl,

Thanks for trying our tutorial. Unfortunately, we are not sure how to do that either. I would recommend posting this issue in the STM dev community to see if someone can help.

**Comment by meenchen** [comment]
Close due to inactivity. Feel free to reopen.
