### ISSUE TITLE
STM32CubeIDE version

### ISSUE THREAD

**Issue by byuljwa** [mit-han-lab/tinyengine#53]
Hello, I tried the vww example with the stm32f746-disco board. However, as written, it works well in version 1.5.0, but I hope there is a place where I can find the reason and solution for not running in 1.11.0.

**Comment by meenchen** [comment]
Hi @byuljwa,

We found that somehow the later version does not work with our camera driver, so that's the reason we use 1.5.0 in the tutorial. But everything else should work well in other versions.

**Comment by byuljwa** [comment]
Thank you. camera driver mean ov2640.h? Which part do I need to edit?

**Comment by meenchen** [comment]
> Thank you. camera driver mean ov2640.h? Which part do I need to edit?

We did not identify the root cause, so it is not clear which part needs to be edited.

**Comment by byuljwa** [comment]
Thanks, I'll research more about this
