### ISSUE TITLE
KWS Model availability 

### ISSUE THREAD

**Issue by kumarchaitanyab** [mit-han-lab/tinyengine#62]
Hi @meenchen, is there a KWS model and its source code available as mentioned in Paper1, if yes can you please provide it? else is there any reason why the model is not available and also let us know by when it can be made available?

**Comment by meenchen** [comment]
Hi @kumarchaitanyab, thanks for reaching out. @tonylins, can we release the KWS model in the mcunet repo?

**Comment by meenchen** [comment]
Close due to inactivity. Feel free to reopen.
