### ISSUE TITLE
keras model for the mcunet-5-fps-vww model

### ISSUE THREAD

**Issue by brainchip-india** [mit-han-lab/tinyengine#64]
Hi @meenchen, can I get the base keras model of mcunet-5-fps-vww model prior converting it to tflite?
Thanks.

**Comment by meenchen** [comment]
Hi @brainchip-india, unfortunately, we don't have the base keras model as we directly convert pytorch model to tflite.

**Comment by brainchip-india** [comment]
Thanks @meenchen.
