### ISSUE TITLE
the code of the audio demo

### ISSUE THREAD

**Issue by lange-bleu** [mit-han-lab/tinyengine#77]
Hi there,
It's so fantastic to deploy a model on an mcu.
Inspired by your paper，I wanna implement an intelligent doorlock with offline speaker verification system.
However,I cannot find the demo code of KWS model mentioned in the paper.Could you please share it?

Thanks a lot

**Comment by meenchen** [comment]
Hi @lange-bleu,

Unfortunately, we do not have the audio demo and mainly focus on visual models, but the model architecture is basically identical. Please check our mcunet repo for more information about the models https://github.com/mit-han-lab/mcunet.

**Comment by lange-bleu** [comment]
ok,what a pity

thanks a lot @meenchen
