### ISSUE TITLE
visual wake word (VWW) model end to end workflow?

### ISSUE THREAD

**Issue by ramkumarkoppu** [mit-han-lab/tinyengine#8]
Hi,

Where do I find jupyter notebook of given example visual wake word (VWW) model in the tutorial folder if I want to check it's model architecture and how it is optimized for MCU (pruned, quantized, model conversion (how C/C++ code is generated from the model)) to follow end to end workflow?

**Comment by meenchen** [comment]
Hi @ramkumarkoppu, thanks for your interest in our work. For the model optimization, please refer to our [mcunet repo.](https://github.com/mit-han-lab/mcunet) We also have a model zoo where you can download the pre-trained models and check their model architecture. Then, you can follow these [examples](https://github.com/mit-han-lab/tinyengine/tree/master/examples) to generate C/C++ code.

**Comment by ramkumarkoppu** [comment]
Hi @meenchen, Do we have corresponding jupyter notebook for vww model? if yes, where do I find it.

**Comment by tonylins** [comment]
Hi, currently we do not have a jupyter notebook for the example. But I think the provided code works the same.

**Comment by ramkumarkoppu** [comment]
Hi, I am interested to understand how fp32 PyTorch model is pruned, quantised before converting into C code. Where do I find the relevant code in the repo?

**Comment by meenchen** [comment]
Close due to inactivity. Feel free to reopen.
